//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediPrime.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    
    public partial class Doctor
    {
        public int Doctor_Id { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }

        [Compare("Password", ErrorMessage = "Password and Confirmation Password must match.")]
        public string Cpassword { get; set; }
        public Nullable<int> Experience { get; set; }
        public string Type { get; set; }
        public string Degree { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Hospital_Name { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
    }

    public enum degreetype
    {
        BDS,
        BAMS,
        BUMS,
        BHMS,
        MBBS,
        MD,
        MS,
        DNB
    }

    public enum doctortype
    {
        Neurologist,
        Immunologist,
        Nephrologist,
        Orthopedist,
        Oncologist,
        Urologist,
        Cardiologist,
        Otolaryngologist,
        Anesthesiologist
    }
}
