//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediPrime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int medicine_id { get; set; }
        public string medicine_name { get; set; }
        public string medicine_catagory { get; set; }
        public Nullable<int> medicine_doserate { get; set; }
        public string medicine_form { get; set; }
        public string medicine_class { get; set; }
    }

    public enum medicineclass
    {
        Antibiotics,
        Antipyretics,
        Analgesics,
        Antiseptics,
        Antimalarial,
        Statins,
        Stimulants
    }

    public enum medicineform
    {
        Liquid,
        Tablet,
        Capsule,
        Drop,
        Inhalers,
        Injection
    }

    public enum medicinecatagory
    {
        Neurologist,
        Immunologist,
        Nephrologist,
        Orthopedist,
        Oncologist,
        Urologist,
        Cardiologist,
        Otolaryngologist,
        Anesthesiologist
    }
}
